### ISSUE TITLE
Setup Backend

### ISSUE THREAD

**Issue by coffeemakingtoaster** [dopeshot/beyond-life#1]

**Comment by coffemakingtoaster** [comment]
![Image](https://github.com/dopeshot/beyond-life/assets/48368581/5a410bd5-c789-44e7-b626-4f6eb6e08f07)

**Comment by coffemakingtoaster** [comment]
![image](https://github.com/dopeshot/beyond-life/assets/48368581/49b1af9b-cc10-48de-81e5-136d5b5a1462)
