### ISSUE TITLE
Shadow Profile Design

### ISSUE THREAD

**Issue by LarsFlieger** [dopeshot/beyond-life#162]
Machen wir

1. erstellen ein Shadow profile auf dem Server mit ID 
2. speichern wir das testament lokal und schicken es bei anmeldung zum server?

**Comment by coffemakingtoaster** [comment]
> Ich würde die 2 Möglichkeit nehmen. Scheint einfacher zu sein und ich sehe keinen großen Vorteil für den Mehraufwand.

Ich auch nicht, lass so machen
Danke  :rocket:
