### ISSUE TITLE
Backend Cleanup

### ISSUE THREAD

**Issue by coffemakingtoaster** [dopeshot/beyond-life#232]
TODO:
- [x] #280

*Tests*
- [x] Test modules and main.ts replacements should match definitions there such as validation options
- [x] #329
 Tests check if beforeEach is slower than beforeAll, replace if needed
- [x] #367
- [x] #343

*Validations*
- [x] Fehlerhandling nochmal anschauen
- [x] #360
- [x] Swagger durchgehen und validieren
- [x] Swagger Responses

*Code*
- [x] #327
- [x] Logging
- [x] Code aufraumen

**Comment by LarsFlieger** [comment]
@coffemakingtoaster 

Frontend link in README.md to codecove returned 404:

`https://codecov.siebtesleben.de/main/frontend/index.html`

![image](https://github.com/dopeshot/beyond-life/assets/47084064/c84f17db-3514-46bf-bff9-80d1c90abc68)

**Comment by LarsFlieger** [comment]
![image](https://github.com/dopeshot/beyond-life/assets/47084064/a964a21f-9eec-4e2f-a1e6-9020ff6218c6)

Why can I give you Dates with the DTO of Create Last will. They should be generated on server side and not included in the create dto. 

- [ ] done

**Comment by LarsFlieger** [comment]
Bei fulltext generierung werden daten nicht in deutschem format generiert: 1999-05-27

ist nicht direkt schlimm aber einfach format DE machen

**Comment by LarsFlieger** [comment]
Bei Fulltext sollte rein wie viel auf den financial assets liegt, also 
`Als Erbe meines Vermögens, aufgeteilt auf Sparkasse, Binance, Onvista und Crypowallet, setze ich folgende Personen ein:`
eher zu sowas:
`Als Erbe meines Vermögens, aufgeteilt auf Sparkasse (1.000.000 Euro), Binance (50 Bitcoin), Onvista (750.000 Euro) und Crypowallet (10 Bitcoin), setze ich folgende Personen ein:``

Es ist wichtig wie viel dort liegt für die verbliebenen.

**Comment by LarsFlieger** [comment]
Bei Fulltext sollte der Verwendungszweck dabei sein. Das ist auch wichtig. Wir sollten jeden Content nutzen für die Generierung, wenn man einmal eins erstellt ist man frustriert (auch Kobi) wenn etwas fehlt.
